runtime: python27
api_version: 1
threadsafe: true

instance_class: F1

service: default

handlers:
  # Serve all static files with url ending with a file extension

  - url: /
    secure: always
    static_files: www/index.html
    upload: www/.*

  - url: /(.*\..+)$
    static_files: www/\1
    upload: www/(.*\..+)$

  # Routing for anything (wild card) after
  - url: /.*
    secure: always
    static_files: www/index.html
    upload: www/.*
